import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {resourceDecision,assertCollectorResources,nativeCrashMessage,readMemorySnapshot} from './collector_resources.mjs';
import {writeJsonAtomic} from './collector_storage.mjs';
import {zhaopinCheckpoint} from './zhaopin_checkpoint.mjs';
const GB=1024**3;
const low={CommitLimit:72*GB,CommittedBytes:71.3*GB,AvailableMBytes:16000};
assert.equal(resourceDecision(low).ok,false,'free physical memory does not prove commit headroom');
await assert.rejects(assertCollectorResources(2*GB,async()=>low),e=>e.code==='RESOURCE_PRESSURE');
assert.ok(resourceDecision({CommitLimit:72*GB,CommittedBytes:50*GB,AvailableMBytes:16000}).ok);
assert.equal(resourceDecision({CommitLimit:0}).ok,false);
await assert.rejects(assertCollectorResources(2*GB,async()=>{throw Error('probe failed');}),e=>e.code==='RESOURCE_PRESSURE');
assert.match(nativeCrashMessage(3221226505),/0xC0000409/);
assert.match(nativeCrashMessage(-1073740791),/0xC0000409/);
assert.equal(nativeCrashMessage(1),'');
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'collector-resource-test-')),file=path.join(dir,'checkpoint.json');
await Promise.all(Array.from({length:10},(_,i)=>writeJsonAtomic(file,{page:i,records:[{id:'p'+i}]})));
const state=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(state.page,9);assert.equal(state.records[0].id,'p9');
assert.equal((await fs.readdir(dir)).filter(n=>n.includes('.tmp')).length,0);
const current={keyword:'智能体开发',city:{name:'上海'},total:60,endPage:false,lastPageIndex:1,records:new Map([['a',{number:'a'}]])};
await writeJsonAtomic(file,zhaopinCheckpoint(current));
current.lastPageIndex=2;current.records.set('b',{number:'b'});await writeJsonAtomic(file,zhaopinCheckpoint(current));
const crashed=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(crashed.records.length,2);assert.equal(crashed.complete,false);assert.equal(crashed.last_page_index,2);
current.endPage=true;current.validResponse=true;assert.equal(zhaopinCheckpoint(current).complete,true);
const snapshot=await readMemorySnapshot();
console.log(JSON.stringify({ok:true,checks:['low commit with abundant RAM safely pauses','probe failure fails closed','native crash decoding','concurrent atomic checkpoint writes','mid-city crash retains last saved page'],liveResourceDecision:resourceDecision(snapshot),snapshot,testDir:dir}));
