import assert from 'node:assert/strict';
import {strictRuleSeed,learnRuleSeedModel,matchRuleSeedRole,unlabeledGroups} from './rule-seed-keywords.mjs';
const row=(title,jd)=>({'岗位名称':title,'岗位描述':jd,'检索词':'ai漫剧师','公司名称':'测试公司',row_no:2});
const positive=row('AI短剧编导','岗位职责：根据剧本制作视频，完成镜头剪辑。');
assert.equal(strictRuleSeed(positive),true);
for(const r of [row('软件工程师','开发接口'),row('AI短剧编导','公司介绍：我们创作短剧。岗位职责：开发接口。'),row('AI短剧测试工程师','制作视频测试报告'),row('AI产品实习生','根据剧本制作视频')])assert.equal(strictRuleSeed(r),false);
const cold=learnRuleSeedModel([positive]);
assert.equal(cold.cold_start,true);assert.deepEqual(cold.keywords,[]);
assert.equal(matchRuleSeedRole(positive,cold).matched,true);
assert.equal(matchRuleSeedRole(row('视频剪辑','根据剧本制作视频'),cold).matched,false);
const model={...cold,cold_start:false,keywords:[{term:'剧本',score:1},{term:'镜头',score:1}],minimum_hits:2};
assert.equal(matchRuleSeedRole(row('AI视频创作者','根据剧本制作视频，剪辑镜头。'),model).matched,true);
assert.equal(matchRuleSeedRole(row('AI视频创作者','了解剧本和镜头，岗位职责：开发接口。'),model).matched,false);
assert.equal(matchRuleSeedRole(row('AI产品实习生','根据剧本制作视频，剪辑镜头。'),model).matched,false);
assert.equal(matchRuleSeedRole(row('法务实习生','AI短剧剧本与镜头内容合规筛查，关注AI生成素材版权归属。'),model).matched,false);
const longPositive={...positive,'岗位描述':positive['岗位描述']+'负责剧情节奏和字幕音效后期剪辑，按照项目需求交付完整成片，独立完成视频制作。'};
const duplicate={...longPositive,row_no:3,'公司名称':'另一家公司'};
assert.equal(unlabeledGroups([longPositive,duplicate])[0],unlabeledGroups([longPositive,duplicate])[1]);
console.log(JSON.stringify({ok:true,checks:['strict seeds','query is not evidence','company introduction excluded','cold start','joint expansion','noncreative exclusions','duplicate grouping']}));
