import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createManualSearchSession} from './manual_search_session.mjs';
import {writeJsonAtomic} from './collector_storage.mjs';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'manual-session-'));
const file=path.join(dir,'智联招聘_浏览器会话.json');
let text='正在验证连接安全性',closed=false,front=0;
let url='https://www.zhaopin.com/jobs?jl=530&kw='+encodeURIComponent('智能体开发');
const page={isClosed:()=>closed,bringToFront:async()=>front++,url:()=>url,locator:()=>({innerText:async()=>text,filter:()=>({allInnerTexts:async()=>[]})})};
const session=await createManualSearchSession(dir,'test-task',page,{pollMs:10});
const current={keyword:'智能体开发',city:{name:'北京',code:'530'},responseError:'old challenge response'};
let returned=false;
const work=session.guard(current).then(()=>returned=true);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function state(){return JSON.parse(await fs.readFile(file,'utf8'));}
for(let i=0;i<100&&(await state()).verification_status!=='waiting_human';i++)await wait(10);
const first=await state();assert.equal(first.login_status,'unknown');assert.equal(front,1);
await writeJsonAtomic(file+'.confirm.json',{task_id:'wrong-task',session_id:first.session_id,confirmed_at:'1'});
await wait(50);assert.equal(returned,false);
await writeJsonAtomic(file+'.confirm.json',{task_id:'test-task',session_id:first.session_id,confirmed_at:'2'});
await wait(50);assert.equal(returned,false);assert.equal((await state()).verification_status,'waiting_human');
text='职位列表';url='https://www.zhaopin.com/';
await writeJsonAtomic(file+'.confirm.json',{task_id:'test-task',session_id:first.session_id,confirmed_at:'3'});
await wait(50);assert.equal(returned,false);
url='https://www.zhaopin.com/jobs?jl=530&kw='+encodeURIComponent('智能体开发');
await writeJsonAtomic(file+'.confirm.json',{task_id:'test-task',session_id:first.session_id,confirmed_at:'4'});
await work;
assert.equal((await state()).session_id,first.session_id);assert.equal((await state()).login_status,'human_confirmed');
assert.equal((await state()).verification_status,'clear');assert.equal(current.responseError,'');
text='请先登录';const second=session.guard(current);await wait(30);closed=true;
await assert.rejects(second,/浏览器已关闭/);await session.close();assert.equal((await state()).browser_open,false);
console.log('PASS: same-session human verification, wrong task rejection, blocked confirmation rejection, exact search scope, close safely');
closed=false;text='';url='about:blank';
const fish=await createManualSearchSession(dir,'fish-task',page,{platform:'yupao',pollMs:10,settleMs:100});
const fishFile=path.join(dir,'鱼泡直聘_浏览器会话.json');
setTimeout(()=>{text='鱼泡职位搜索';url='https://www.yupao.com/zhaogong/a1c0/';},30);
await fish.guard({keyword:'智能体开发',city:{name:'北京'}});
assert.equal(JSON.parse(await fs.readFile(fishFile,'utf8')).verification_status,'clear','transient blank waits for hydration');
text='';url='about:blank';
const fishWait=fish.guard({keyword:'智能体开发',city:{name:'北京'}});
await wait(180);
const fishState=JSON.parse(await fs.readFile(fishFile,'utf8'));
assert.equal(fishState.verification_status,'waiting_human');assert.equal(fishState.platform,'yupao');
text='鱼泡职位搜索';url='https://www.yupao.com/zhaogong/a1c0/';
await writeJsonAtomic(fishFile+'.confirm.json',{task_id:'fish-task',session_id:fishState.session_id,confirmed_at:'fish-confirm'});
await fishWait;await fish.close();
console.log('PASS: Yupao transient blank recovery and permanent blank human confirmation in same session');
