import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {initializeLocalBrowserProfile} from './browser_local_initialization.mjs';

const root=await fs.mkdtemp(path.join(os.tmpdir(),'local-browser-initialization-test-'));
const source=path.join(root,'source'),configFile=path.join(root,'sources.json');
await fs.mkdir(path.join(source,'Default','Network'),{recursive:true});
await fs.mkdir(path.join(source,'Default','Sessions'));
await fs.mkdir(path.join(source,'Default','Cache'));
await fs.writeFile(path.join(source,'Default','Network','Cookies'),'opaque encrypted fixture');
await fs.writeFile(path.join(source,'Default','Sessions','Session_fixture'),'old tabs');
await fs.writeFile(path.join(source,'Default','Cache','fixture'),'cache');
const prefs={intl:{accept_languages:'zh-CN,en'},spellcheck:{dictionaries:['zh-CN']},account_info:[{fixture:'private-account'}],session:{restore_on_startup:1,startup_urls:['https://example.invalid/old-tab']}};
await fs.writeFile(path.join(source,'Default','Preferences'),JSON.stringify(prefs));
await fs.writeFile(path.join(source,'Local State'),JSON.stringify({os_crypt:{encrypted_key:'opaque-key-fixture'},profile:{info_cache:{Default:{name:'fixture'},'Profile 1':{name:'other'}},last_used:'Profile 1'}}));
const before=await fs.readFile(path.join(source,'Default','Preferences'),'utf8');
const full={mode:'full',source_root:source,source_profile:'Default',seed_dir:path.join(root,'seed')};
await fs.writeFile(configFile,JSON.stringify({platforms:{yupao:{isolated:full,standard:{mode:'settings',source_root:source,source_profile:'Default'}}}}));
process.env.JOB_BROWSER_SOURCE_CONFIG=configFile;
const edge=path.join(root,'edge'),chrome=path.join(root,'chrome');
await fs.mkdir(edge);await fs.mkdir(chrome);
const imported=await initializeLocalBrowserProfile('yupao',edge,'isolated');assert.equal(imported.metadata.mode,'full');
assert.equal(await fs.readFile(path.join(edge,'Default','Network','Cookies'),'utf8'),'opaque encrypted fixture');
assert.equal(await fs.readFile(path.join(source,'Default','Preferences'),'utf8'),before);
await assert.rejects(fs.access(path.join(edge,'Default','Sessions')));
const edgePrefs=JSON.parse(await fs.readFile(path.join(edge,'Default','Preferences'),'utf8'));assert.deepEqual(edgePrefs.session.startup_urls,[]);assert.equal(edgePrefs.session.restore_on_startup,5);
await fs.writeFile(path.join(edge,'Default','Network','Cookies'),'target changes');
await initializeLocalBrowserProfile('yupao',edge,'isolated');assert.equal(await fs.readFile(path.join(edge,'Default','Network','Cookies'),'utf8'),'target changes');
await fs.mkdir(path.join(chrome,'Default'));await fs.writeFile(path.join(chrome,'Default','Preferences'),JSON.stringify({account_info:[{fixture:'existing-account'}],existingMarker:'retained'}));
const settings=await initializeLocalBrowserProfile('yupao',chrome,'standard');assert.equal(settings.metadata.mode,'settings');
const chromePrefs=JSON.parse(await fs.readFile(path.join(chrome,'Default','Preferences'),'utf8'));assert.equal(chromePrefs.intl.accept_languages,'zh-CN,en');assert.equal(chromePrefs.existingMarker,'retained');assert.equal(chromePrefs.account_info[0].fixture,'existing-account');
await assert.rejects(fs.access(path.join(chrome,'Default','Network','Cookies')));
assert.equal((await initializeLocalBrowserProfile('zhaopin',path.join(root,'other'),'isolated')).metadata,null);
console.log(JSON.stringify({ok:true,checks:['full profile snapshot copies encrypted data without decrypting','source data unchanged','old sessions and cache excluded','snapshot reused without overwriting current login','Chrome imports settings and preserves existing account data','Chrome does not import Edge credentials','other platforms unchanged']}));
